### ISSUE TITLE
react-hooks-props-basics-lab

### ISSUE THREAD

**Issue by shaniburde** [learn-co-curriculum/react-hooks-props-basics-lab#4]
### Canvas Link

https://learning.flatironschool.com/courses/4566/assignments/161368?module_item_id=345773

### Concern

The test seems to be checking for "username" instead of "name" in the 'About' section of the lab.

The data object has "name" as the key.

The tests check for "username".

### Suggested Changes

Change the tests to look for "name" instead of "username" in the 'About' section.

**Comment by ihollander** [comment]
Hi @shaniburde - thanks for your feedback! I can see how this isn't clear. If you look at the [solution](https://github.com/learn-co-curriculum/react-hooks-props-basics-lab/blob/solution/src/components/App.js), you can see it's possible to get the tests passing by using a prop called `username` to pass the data from the `name` key down to the `<Home>` component. However I agree that the instructions for this could be clearer and more consistent. 

We'll make some updates to help clarify this deliverable. Appreciate your input!
